os:
  - linux

matrix:
  include:
    - language: python
      script:
        - pip install -r dependencies/requirements.txt

    - language: node_js
      node_js:
        - "10"
      before_script:
        - npm install -g surge
      script:
        - grunt build
        - ls
        - surge --project ./build/ --domain "pr-${TRAVIS_PULL_REQUEST}-numpy-versions.surge.sh"
