language: generic
os:
  - linux

before_script:
  - pip install -r dependencies/requirements.txt
  - npm install -g surge

script:
  - grunt build
  - ls
  - surge --project ./build/ --domain "pr-${TRAVIS_PULL_REQUEST}-numpy-versions.surge.sh"
